### ISSUE TITLE
Tracklist unavailable

### ISSUE THREAD

**Issue by anewuser** [trepDev/mixcloud-with-tracklist#1]
Can you please check if this one is really blocked? Apparently, the uploader has added track titles, but I get a "Tracklist unavailable" error with your extension.

https://www.mixcloud.com/cyrus-grissom/gruv-house-07232018/

Firefox 62.0

**Comment by trepDev** [comment]
Hi,
Tracklist is displaying with no problem on my side (with firefox 62)

![gruvhouse](https://user-images.githubusercontent.com/43113963/45595139-6e89c600-b9a7-11e8-92c8-f1446beac577.png)

edit:
If your problem is still here, can you give me a navigation scenario to reproduce your problem?

**Comment by anewuser** [comment]
I just logged in and then opened that URL. Mixcloud isn't showing me the track names while they are being played either. I don't know what's causing it. I've even tried a clean profile but the result was the same.

**Comment by trepDev** [comment]
Can you tell me if you have this issue only on this mix or on all of them?
I retried your mix on others computers today, still no issue :/

**Comment by anewuser** [comment]
It affects other mixes too. Since it doesn't show anything while songs are played either (with no extensions installed), it's out of your control.

**Comment by trepDev** [comment]
Actually, I think you're right.
I've got same issue this morning. During 10 min, Mixcloud returns all datas except tracklist, even on its own requests!
So I close this issue, but I need to add some delayed requests on empty Mix (for now, I assume that empty mix is really empty & don't request about it again)

**Comment by anewuser** [comment]
I just tried it again and now everything works on the first try. 

@adlawson @fshauge You may want to take a look at this new extension and contribute to it/point users to it instead of reinventing the wheel.
