### ISSUE TITLE
copy paste tracklist introduces \n

### ISSUE THREAD

**Issue by pestrela** [trepDev/mixcloud-with-tracklist#2]
I love this chrome extension. Many thanks for this.

Only issue is that when I copy the playlist the table columns are seperated by "\n"
could they please be separated by "-"?

Alterntivellty, could you add a button to copy the tracklist to clipboard like 1001tracklists does?

thanks again

**Comment by trepDev** [comment]
Hi, glad you like it :)

This is a good idea. I will add a copy button, but not right now (lot of professional & personal work to do).
But I'll check that  this month :)

**Comment by pestrela** [comment]
I see that you coded the feature, thank you
can you make a new chrome plugin release? I'm on 2.1.0

**Comment by trepDev** [comment]
I will make a new release very soon (most likely this weekend) :)

**Comment by trepDev** [comment]
Release 2.2.0 available on Chrome and Firefox Store.
You can now copy tracklist to clipboard :)

**Comment by pestrela** [comment]
perfect, works fine now!
many thanks for your work and this useful extension
