### ISSUE TITLE
Tracklist unavailable

### ISSUE THREAD

**Issue by Hierrbatnik** [trepDev/mixcloud-with-tracklist#27]
Hi, 
Once again tracklist is not displayed, no reaction at all, 
Would You please look at it?
cheers

![Screen Shot 09-16-23 at 07 53 AM](https://github.com/trepDev/mixcloud-with-tracklist/assets/145183490/d9fa3cd7-4c56-495b-a89e-4d9a99ab0328)

**Comment by trepDev** [comment]
Hi @Hierrbatnik ,
Thx for the issue.
The extension is broken due to modifications made on the website.
A new version of Mixcloud with Tracklist should be available within 1/2 days (depending on the store validation delay).

**Comment by Hierrbatnik** [comment]
Thank You so much :)
