### ISSUE TITLE
Swap song name with artist, to make artist first.

### ISSUE THREAD

**Issue by Pycur** [trepDev/mixcloud-with-tracklist#35]
Hello!
It's not a really issue, I just prefer to display songs details in this order.
Is there any way to render the list in a table? I can switch columns easily from then.
Or just make an option what to show first in the settings.
Thank you for this awesome useful extension. :)

**Comment by trepDev** [comment]
Hi @Pycur,

I think I will indeed switch artist & song in the table. Even the paid Mixcloud version displays mix information in this order.
A small extension update is planned soon, so I will include your request in it.
It's great to hear that the extension is useful.

**Comment by Pycur** [comment]
Thanks for the positive reply.
I usually download what I like for later use, internet sources are not reliable for long years, and I put all the info I found in a txt file. Like these tracklist, to have any clue what i'm hearing then...
I used to use chrome inspector and find these myself, but getting these in a click will speed up my work.
Thanks!
Btw this plugin does not find any tracklist right not, not even that ones it found earlier. 
Do you have any idea which cache or something need to be deleted to make it work again? Or it just mixclouds development...

**Comment by trepDev** [comment]
Strange. I just use my extension right now, and I have no issue.
Can you give me a previously working link which seems to not work anymore?

**Comment by Pycur** [comment]
Strange enough. Now it works.... this was the one that worked earlier, than yesterday not, and every other too, now works again:
https://www.mixcloud.com/jayfrog/strobe-light-essentials-014/

**Comment by trepDev** [comment]
Yep works for me.

The tracklist data is retrieved directly from Mixcloud.
When I launched this extension (5 years ago ^^), I recall that Mixcloud would sometimes not return any tracklists for some minutes. It's probable that they have a bug.
But it's been a long time since it happened to me.
